# Data
path: /content/drive/MyDrive/Thesis/POV_Surgery_data-YOLO_format
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Keypoints
kpt_shape: [21, 2]  # [number of keypoints, number of dim]

# Classes
names:
  0: hand